# Basic System
CONFIG_GPIO=y
CONFIG_PRINTK=y
CONFIG_CBPRINTF_FP_SUPPORT=y 

# ESB Configuration
CONFIG_ESB=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=32

# RTT Console Logging
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_STDOUT_CONSOLE=y

# MANDATORY HARDWARE CLOCK FIX (Internal RC Oscillator)
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y

# for reference https://github.com/nrfconnect/sdk-nrf/blob/fbcdd8cc23fb193c30e6e4e87bf9d0ae0c2ff943/include/esb.h#L307 and https://github.com/nrfconnect/sdk-nrf/blob/main/subsys/esb/esb.c
